name: Lint and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js =14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Use Golang =1.16.2
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.2'
      # Install `tinygo`
      - run: wget https://github.com/tinygo-org/tinygo/releases/download/v0.17.0/tinygo_0.17.0_amd64.deb
      - run: sudo dpkg -i tinygo_0.17.0_amd64.deb
      - run: export PATH=$PATH:/usr/local/tinygo/bin

      - run: yarn
      - run: yarn lint
      - run: yarn compile
      - run: yarn test:unit
      - run: yarn build
      - run: yarn start &
      - run: yarn test:e2e
