name: Lint and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js =14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Use Golang =1.16.2
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.2'
      - run: yarn
      - run: yarn lint
      - run: yarn compile
      - run: yarn test:unit
      - run: yarn build
      - run: yarn start &
      - run: yarn test:e2e
