name: Lint and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js =14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Use Golang =1.16.2
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.2'

      # Install `tinygo`.
      - run: wget https://github.com/tinygo-org/tinygo/releases/download/v0.17.0/tinygo_0.17.0_amd64.deb
      - run: sudo dpkg -i tinygo_0.17.0_amd64.deb
      - run: export PATH=$PATH:/usr/local/tinygo/bin

      # Compile, lint and unit test packages.
      - run: yarn
      - run: yarn compile
      - run: yarn lint
      - run: yarn test:unit

      # Run e2e tests with Cypress.
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install-command: yarn
          build: yarn build
          start: yarn start
          command: yarn test:e2e
          wait-on: 'http://localhost:3000'
